name: postgresql
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: dynamicfb
      POSTGRES_PASSWORD: dynamicfb
      POSTGRES_DB: dynamicfb
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
